baseurl = "https://blog.fwendlandt.net/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Fabian Wendlandt"
title = "Fabian's Blog"
disqusshortname = "fwendlandt"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Fabian's Blog"
copyright = "Copyright Â© 2017 Fabian Wendlandt"
logofile = "img/blog.png"
latestpostcount = 5
faviconfile = "img/blog.png"
highlightjs = true
progressively = false
lang = "en"
github = "watschi"
email = "fabian-wendlandt@gmx.de"
social_banner = "img/Foto.jpg"
posts_navigation = true
share = true
